nome_1 = input('Dammi un nome di cosa plurale ')
verbo = input('Dammi un verbo terminante in -ato ')
nome_2 = input('Dammi un altro nome di cosa plurale ')
nome_3 = input('Dammi un nome di cosa ')
aggettivo = input('Dammi un aggettivo ')
cibo_1 = input('Dammi un cibo ')
cibo_2 = input('Dammi un altro cibo ')
nome_4 = input('Dammi un nome di cosa ')
nome_5 = input('un altro ancora ')
nome_6 = input('e un ultimo ancora ')

print('Il gelato è un dessert surgelato a base di ' + nome_1 + ', con aggiunta di aromi e dolcificanti.')
print('Questa miscela viene rapidamente congelata mentre viene ' + verbo + ', in modo che non si formino ' + nome_2 + '.')
print('Alcuni gelati sono fatti con ' + nome_3 + ', estratto da alghe, in modo che non sia ' + aggettivo + '.')
print('Ci sono molti diversi gusti di gelato, come ' + cibo_1 + ' e ' + cibo_2+ '.')
print('Il gelato spesso ha delle aggiunte per insaporire, come ' + nome_4 + ', ' + nome_5 + ' o ' + nome_6 + '.')
